### PR TITLE
v11

### PR DESCRIPTION
**Pull request by peterlewis**
Add ability to listen on other interfaces and bump NodeJS and deps

### CODE REVIEW

**Comment by rahilarious** [comment]
btw did you know upstream is looking for maintainer? Take a look https://github.com/wg-easy/wg-easy/discussions/553

**Comment by peterlewis** [comment]
@pheiduck I think this is good to go, but keen to test some more prior to hitting prod. Can you please give the latest nightly a once/twice-over? Thanks! :)

**Comment by pheiduck** [comment]
I only see that the checksum for node 18 is incorrect should be this:
`435dcad253bb5b7f347ebc69c8cc52de7c912eb7241098b920f2fc2d7843183d`

**Comment by peterlewis** [comment]
Oh crumbs! You're right. Sorry, I stupidly used the hash for the architecture.

**Pull request merged**
