### PR TITLE
Ability to change ip address WebUI binds to with WEBUI_HOST env var

### PR DESCRIPTION
**Pull request by rahilarious**

### CODE REVIEW

**Comment by peterlewis** [comment]
Hi there! Thank you for the PR! Can you please clarify in what context someone would want to change the Web UI host from `0.0.0.0` to an alternative?

**Comment by rahilarious** [comment]
In scenarios where there are 2 interfaces, one with public ip & other private. One might want to restrict frontend to private interface only.

**Comment by peterlewis** [comment]
Ah I understand, thank you. Whilst somewhat of an infrequent requirement, I can appreciate why it might be useful/valuable, and it defaults to `0.0.0.0` so thank you for the PR and will get this merged.

Will aim to expand upon the readme, so as to make clear the use-cases for these sorts of advanced variables.

**Comment by peterlewis** [comment]
Just to add, this will be included in the next push to Production (which is to be imminent, I think). In the meantime, if you want to reap the benefits then feel free to shift to `:nightly`.

Thanks! :)

**Comment by rahilarious** [comment]
on :nightly since day 1. Bleeding ftw. ;⁠-⁠)

**Pull request merged**
